### ISSUE TITLE
Need Schematics, please~

### ISSUE THREAD

**Issue by starock** [eqy/ymduino#1]
I love this project.  Whats arduino board in used? UNO?

Really need the schematics. Thanks alot!

**Comment by eqy** [comment]
Yes, it was done using an UNO. Unfortunately I didn't really draw up a schematic when I did the design because there were very few components used.
The comments for the pinouts in the `.ino` file should roughly line up with what you'll find [here](http://www.ym2149.com/ym2149.pdf). Other than that a 2 MHz signal (either via crystal oscillator or other method) and a 1k ohm resistor for the output should be all you need to get off the ground.
You should be able to discern which pins were used for control based on the use of `PORTD` and the masks--the control signals are also documented in the pdf linked above.

If you're starting from scratch, I would recommend using the version of the sketch [@26d303a](https://github.com/eqy/ymduino/blob/26d303a7aff50b4aa053f3740203cf825e17a10b/ymduino.ino), since it doesn't have any of the code used to read data off of the microSD card. 

Hope that helps!

**Comment by starock** [comment]
Thank you for reply. I'll try  @26d303a.  Actually,my question is: YM2149's pin29\28\27 should connect to which pin on the UNO? Pin 2\3?
--------------

Yeah! I did it!~ Thanks!

YM2149  pin29 -> UNO pin2
YM2149  pin27 -> UNO pin3

then run a python YM streamer send data to UNO.  Music! lol
